// АВТОГЕНЕРАЦИЯ из internal/data/clubs.go + логотипы TheSportsDB.
// 132 клуба (53 сборные → флаг emoji, 79 клубов → реальный крест-логотип).
// Битый логотип грациозно падает на градиентный бейдж (см. PlayerAvatar).

export interface ClubInfo {
  id: string;
  name: string;
  nameRu: string;
  color: string;
  color2: string;
  logo: string;        // emoji-флаг для сборных, ⚽ для клубов
  logoUrl?: string;    // URL креста (TheSportsDB)
  isNational: boolean;
}

const CLUB_DATA: ClubInfo[] = [
  { id: "real_madrid", name: "Real Madrid", nameRu: "Реал Мадрид", color: "#ffffff", color2: "#1a3c8c", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/vwvwrw1473502969.png" },
  { id: "barcelona", name: "Barcelona", nameRu: "Барселона", color: "#a50044", color2: "#004d98", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/wq9sir1639406443.png" },
  { id: "man_city", name: "Manchester City", nameRu: "Манчестер Сити", color: "#6cabdd", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/vwpvry1467462651.png" },
  { id: "man_utd", name: "Manchester United", nameRu: "Манчестер Юнайтед", color: "#da291c", color2: "#fbe122", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/xzqdr11517660252.png" },
  { id: "liverpool", name: "Liverpool", nameRu: "Ливерпуль", color: "#c8102e", color2: "#f6eb61", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/kfaher1737969724.png" },
  { id: "chelsea", name: "Chelsea", nameRu: "Челси", color: "#034694", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/yvwvtu1448813215.png" },
  { id: "arsenal", name: "Arsenal", nameRu: "Арсенал", color: "#ef0107", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/uyhbfe1612467038.png" },
  { id: "psg", name: "Paris Saint-Germain", nameRu: "ПСЖ", color: "#003170", color2: "#da291c", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/26f50y1705434178.png" },
  { id: "bayern", name: "Bayern München", nameRu: "Бавария", color: "#dc052d", color2: "#0066b2", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/01ogkh1716960412.png" },
  { id: "dortmund", name: "Borussia Dortmund", nameRu: "Боруссия Дортмунд", color: "#fde100", color2: "#000000", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/tqo8ge1716960353.png" },
  { id: "juventus", name: "Juventus", nameRu: "Ювентус", color: "#000000", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/uxf0gr1742983727.png" },
  { id: "inter", name: "Inter Milan", nameRu: "Интер", color: "#003399", color2: "#000000", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/ryhu6d1617113103.png" },
  { id: "ac_milan", name: "AC Milan", nameRu: "Милан", color: "#fb090b", color2: "#000000", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/wvspur1448806617.png" },
  { id: "atletico", name: "Atlético Madrid", nameRu: "Атлетико", color: "#ce3524", color2: "#272e6b", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/0ulh3q1719984315.png" },
  { id: "chelsea_w", name: "Ajax", nameRu: "Аякс", color: "#d2122e", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/zg9tii1755495289.png" },
  { id: "brazil", name: "Brazil", nameRu: "Бразилия", color: "#009c3b", color2: "#fedf00", logo: "🇧🇷", isNational: true },
  { id: "argentina", name: "Argentina", nameRu: "Аргентина", color: "#74acdf", color2: "#ffffff", logo: "🇦🇷", isNational: true },
  { id: "france", name: "France", nameRu: "Франция", color: "#002395", color2: "#ffffff", logo: "🇫🇷", isNational: true },
  { id: "england", name: "England", nameRu: "Англия", color: "#ffffff", color2: "#cf081f", logo: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", isNational: true },
  { id: "germany", name: "Germany", nameRu: "Германия", color: "#ffffff", color2: "#000000", logo: "🇩🇪", isNational: true },
  { id: "spain", name: "Spain", nameRu: "Испания", color: "#c60b1e", color2: "#ffc400", logo: "🇪🇸", isNational: true },
  { id: "portugal", name: "Portugal", nameRu: "Португалия", color: "#006600", color2: "#ff0000", logo: "🇵🇹", isNational: true },
  { id: "italy", name: "Italy", nameRu: "Италия", color: "#003399", color2: "#ffffff", logo: "🇮🇹", isNational: true },
  { id: "uzbekistan", name: "Uzbekistan", nameRu: "Узбекистан", color: "#1eb53a", color2: "#0099b5", logo: "🇺🇿", isNational: true },
  { id: "tajikistan", name: "Tajikistan", nameRu: "Таджикистан", color: "#cc0000", color2: "#006600", logo: "🇹🇯", isNational: true },
  { id: "tottenham", name: "Tottenham Hotspur", nameRu: "Тоттенхэм", color: "#ffffff", color2: "#132257", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/dfyfhl1604094109.png" },
  { id: "newcastle", name: "Newcastle United", nameRu: "Ньюкасл", color: "#241f20", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/lhwuiz1621593302.png" },
  { id: "aston_villa", name: "Aston Villa", nameRu: "Астон Вилла", color: "#670e36", color2: "#95bfe5", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/jykrpv1717309891.png" },
  { id: "west_ham", name: "West Ham United", nameRu: "Вест Хэм", color: "#7a263a", color2: "#1bb1e7", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/yutyxs1467459956.png" },
  { id: "brighton", name: "Brighton & Hove Albion", nameRu: "Брайтон", color: "#0057b8", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/zn0x7h1605371909.png" },
  { id: "wolves", name: "Wolverhampton", nameRu: "Вулверхэмптон", color: "#fdb913", color2: "#231f20", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/u9qr031621593327.png" },
  { id: "crystal_palace", name: "Crystal Palace", nameRu: "Кристал Пэлас", color: "#1b458f", color2: "#c4122e", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/ia6i3m1656014992.png" },
  { id: "fulham", name: "Fulham", nameRu: "Фулхэм", color: "#ffffff", color2: "#000000", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/xwwvyt1448811086.png" },
  { id: "brentford", name: "Brentford", nameRu: "Брентфорд", color: "#e30613", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/grv1aw1546453779.png" },
  { id: "everton", name: "Everton", nameRu: "Эвертон", color: "#003399", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/eqayrf1523184794.png" },
  { id: "nottingham", name: "Nottingham Forest", nameRu: "Ноттингем Форест", color: "#dd0000", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/1i2kvh1719918076.png" },
  { id: "leeds", name: "Leeds United", nameRu: "Лидс", color: "#ffffff", color2: "#1d428a", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/jcgrml1756649030.png" },
  { id: "sevilla", name: "Sevilla", nameRu: "Севилья", color: "#d8112a", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/vpsqqx1473502977.png" },
  { id: "real_betis", name: "Real Betis", nameRu: "Бетис", color: "#00954c", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/2oqulv1663245386.png" },
  { id: "villarreal", name: "Villarreal", nameRu: "Вильярреал", color: "#ffe667", color2: "#005187", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/vrypqy1473503073.png" },
  { id: "real_sociedad", name: "Real Sociedad", nameRu: "Реал Сосьедад", color: "#0067b1", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/vptvpr1473502986.png" },
  { id: "athletic", name: "Athletic Bilbao", nameRu: "Атлетик Бильбао", color: "#ee2523", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/68w7fe1639408210.png" },
  { id: "valencia", name: "Valencia", nameRu: "Валенсия", color: "#ffffff", color2: "#f18e00", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/dm8l6o1655594864.png" },
  { id: "girona", name: "Girona", nameRu: "Жирона", color: "#d50032", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/kfu7zu1659897499.png" },
  { id: "celta", name: "Celta Vigo", nameRu: "Сельта", color: "#8ac3ee", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/xfjtku1690436219.png" },
  { id: "napoli", name: "Napoli", nameRu: "Наполи", color: "#12a0d7", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/l8qyxv1742982541.png" },
  { id: "roma", name: "AS Roma", nameRu: "Рома", color: "#8e1f2f", color2: "#f0bc42", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/jwro2s1760820674.png" },
  { id: "lazio", name: "Lazio", nameRu: "Лацио", color: "#87d8f7", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/rwqyvs1448806608.png" },
  { id: "atalanta", name: "Atalanta", nameRu: "Аталанта", color: "#1d1d1b", color2: "#005ca9", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/qix5ku1780561327.png" },
  { id: "fiorentina", name: "Fiorentina", nameRu: "Фиорентина", color: "#592c82", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/hc8nhu1656098030.png" },
  { id: "bologna", name: "Bologna", nameRu: "Болонья", color: "#1a2f48", color2: "#a01e20", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/2qi1u31655592366.png" },
  { id: "torino", name: "Torino", nameRu: "Торино", color: "#881600", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/xxprty1448806802.png" },
  { id: "leipzig", name: "RB Leipzig", nameRu: "Лейпциг", color: "#dd0741", color2: "#001f47", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/zjgapo1594244951.png" },
  { id: "leverkusen", name: "Bayer Leverkusen", nameRu: "Байер", color: "#e32219", color2: "#000000", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/3x9k851726760113.png" },
  { id: "frankfurt", name: "Eintracht Frankfurt", nameRu: "Айнтрахт", color: "#000000", color2: "#e1000f", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/rurwpy1473453269.png" },
  { id: "wolfsburg", name: "VfL Wolfsburg", nameRu: "Вольфсбург", color: "#65b32e", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/ci9trv1778399557.png" },
  { id: "stuttgart", name: "VfB Stuttgart", nameRu: "Штутгарт", color: "#ffffff", color2: "#e30613", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/yppyux1473454085.png" },
  { id: "gladbach", name: "Borussia M'gladbach", nameRu: "Боруссия М", color: "#ffffff", color2: "#000000", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/sysurw1473453380.png" },
  { id: "freiburg", name: "SC Freiburg", nameRu: "Фрайбург", color: "#000000", color2: "#e2001a", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/dkufe01630021084.png" },
  { id: "marseille", name: "Olympique Marseille", nameRu: "Марсель", color: "#2faee0", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/c6bazh1779212287.png" },
  { id: "lyon", name: "Olympique Lyon", nameRu: "Лион", color: "#ffffff", color2: "#e2001a", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/blk9771656932845.png" },
  { id: "monaco", name: "AS Monaco", nameRu: "Монако", color: "#e51b22", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/fl2ti01649168915.png" },
  { id: "lille", name: "Lille", nameRu: "Лилль", color: "#e01e24", color2: "#001b50", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/txcsg21741597962.png" },
  { id: "nice", name: "OGC Nice", nameRu: "Ницца", color: "#c8102e", color2: "#000000", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/msy7ly1621593859.png" },
  { id: "rennes", name: "Stade Rennais", nameRu: "Ренн", color: "#e23737", color2: "#000000", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/ypturx1473504818.png" },
  { id: "lens", name: "RC Lens", nameRu: "Ланс", color: "#ffe500", color2: "#e2001a", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/3pxoum1598797195.png" },
  { id: "benfica", name: "Benfica", nameRu: "Бенфика", color: "#e30613", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/hj4kyc1781152436.png" },
  { id: "porto", name: "FC Porto", nameRu: "Порту", color: "#00428c", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/86rrtg1628850959.png" },
  { id: "sporting", name: "Sporting CP", nameRu: "Спортинг", color: "#008057", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/ohj6ih1628855978.png" },
  { id: "braga", name: "SC Braga", nameRu: "Брага", color: "#e30613", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/8g4aod1678717261.png" },
  { id: "ajax", name: "Ajax", nameRu: "Аякс", color: "#d2122e", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/zg9tii1755495289.png" },
  { id: "psv", name: "PSV Eindhoven", nameRu: "ПСВ", color: "#ed1c24", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/xfsz6i1721297428.png" },
  { id: "feyenoord", name: "Feyenoord", nameRu: "Фейеноорд", color: "#e30613", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/uturtx1473534803.png" },
  { id: "celtic", name: "Celtic", nameRu: "Селтик", color: "#16973b", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/3uv1641758780002.png" },
  { id: "rangers", name: "Rangers", nameRu: "Рейнджерс", color: "#1b458f", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/ti24j61614290048.png" },
  { id: "galatasaray", name: "Galatasaray", nameRu: "Галатасарай", color: "#a90432", color2: "#fbb800", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/io7jk21767941298.png" },
  { id: "fenerbahce", name: "Fenerbahçe", nameRu: "Фенербахче", color: "#093a7c", color2: "#ffed00", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/twxxvs1448199691.png" },
  { id: "besiktas", name: "Beşiktaş", nameRu: "Бешикташ", color: "#000000", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/svo05k1776827439.png" },
  { id: "shakhtar", name: "Shakhtar Donetsk", nameRu: "Шахтёр", color: "#f47b20", color2: "#000000", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/sqrxsr1421791799.png" },
  { id: "club_brugge", name: "Club Brugge", nameRu: "Брюгге", color: "#005baa", color2: "#000000", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/mz8y0q1771129880.png" },
  { id: "salzburg", name: "RB Salzburg", nameRu: "Зальцбург", color: "#e2001a", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://www.thesportsdb.com/images/media/team/badge/nc2cua1781541639.png" },
  { id: "boca", name: "Boca Juniors", nameRu: "Бока Хуниорс", color: "#003f88", color2: "#fcb813", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/bm7krb1775741582.png" },
  { id: "river_plate", name: "River Plate", nameRu: "Ривер Плейт", color: "#ffffff", color2: "#e6002d", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/03dmi31645539717.png" },
  { id: "flamengo", name: "Flamengo", nameRu: "Фламенго", color: "#c52613", color2: "#000000", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/syptwx1473538074.png" },
  { id: "palmeiras", name: "Palmeiras", nameRu: "Палмейрас", color: "#006437", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/vsqwqp1473538105.png" },
  { id: "corinthians", name: "Corinthians", nameRu: "Коринтианс", color: "#000000", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/vvuvps1473538042.png" },
  { id: "sao_paulo", name: "São Paulo", nameRu: "Сан-Паулу", color: "#ffffff", color2: "#e30613", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/sxpupx1473538135.png" },
  { id: "santos", name: "Santos", nameRu: "Сантос", color: "#ffffff", color2: "#000000", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/j8xk9g1679447486.png" },
  { id: "gremio", name: "Grêmio", nameRu: "Гремио", color: "#0d80bf", color2: "#000000", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/uvpwyt1473538089.png" },
  { id: "netherlands", name: "Netherlands", nameRu: "Нидерланды", color: "#ff7d00", color2: "#ffffff", logo: "🇳🇱", isNational: true },
  { id: "belgium", name: "Belgium", nameRu: "Бельгия", color: "#e30613", color2: "#ffe500", logo: "🇧🇪", isNational: true },
  { id: "croatia", name: "Croatia", nameRu: "Хорватия", color: "#e30613", color2: "#ffffff", logo: "🇭🇷", isNational: true },
  { id: "denmark", name: "Denmark", nameRu: "Дания", color: "#c8102e", color2: "#ffffff", logo: "🇩🇰", isNational: true },
  { id: "switzerland", name: "Switzerland", nameRu: "Швейцария", color: "#d52b1e", color2: "#ffffff", logo: "🇨🇭", isNational: true },
  { id: "poland", name: "Poland", nameRu: "Польша", color: "#ffffff", color2: "#dc143c", logo: "🇵🇱", isNational: true },
  { id: "sweden", name: "Sweden", nameRu: "Швеция", color: "#006aa7", color2: "#fecc00", logo: "🇸🇪", isNational: true },
  { id: "ukraine", name: "Ukraine", nameRu: "Украина", color: "#005bbb", color2: "#ffd500", logo: "🇺🇦", isNational: true },
  { id: "serbia", name: "Serbia", nameRu: "Сербия", color: "#c6363c", color2: "#ffffff", logo: "🇷🇸", isNational: true },
  { id: "turkey", name: "Turkey", nameRu: "Турция", color: "#e30a17", color2: "#ffffff", logo: "🇹🇷", isNational: true },
  { id: "wales", name: "Wales", nameRu: "Уэльс", color: "#c8102e", color2: "#ffffff", logo: "🏴󠁧󠁢󠁷󠁬󠁳󠁿", isNational: true },
  { id: "scotland", name: "Scotland", nameRu: "Шотландия", color: "#0065bd", color2: "#ffffff", logo: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", isNational: true },
  { id: "austria_nt", name: "Austria", nameRu: "Австрия", color: "#ef3340", color2: "#ffffff", logo: "🇦🇹", isNational: true },
  { id: "russia", name: "Russia", nameRu: "Россия", color: "#ffffff", color2: "#d52b1e", logo: "🇷🇺", isNational: true },
  { id: "uruguay", name: "Uruguay", nameRu: "Уругвай", color: "#5cbfeb", color2: "#ffffff", logo: "🇺🇾", isNational: true },
  { id: "colombia", name: "Colombia", nameRu: "Колумбия", color: "#fcd116", color2: "#003893", logo: "🇨🇴", isNational: true },
  { id: "chile", name: "Chile", nameRu: "Чили", color: "#d52b1e", color2: "#0039a6", logo: "🇨🇱", isNational: true },
  { id: "peru", name: "Peru", nameRu: "Перу", color: "#d91023", color2: "#ffffff", logo: "🇵🇪", isNational: true },
  { id: "ecuador", name: "Ecuador", nameRu: "Эквадор", color: "#ffd100", color2: "#0072ce", logo: "🇪🇨", isNational: true },
  { id: "paraguay", name: "Paraguay", nameRu: "Парагвай", color: "#d52b1e", color2: "#0038a8", logo: "🇵🇾", isNational: true },
  { id: "japan", name: "Japan", nameRu: "Япония", color: "#0a1f8f", color2: "#ffffff", logo: "🇯🇵", isNational: true },
  { id: "south_korea", name: "South Korea", nameRu: "Южная Корея", color: "#c60c30", color2: "#003478", logo: "🇰🇷", isNational: true },
  { id: "saudi_arabia", name: "Saudi Arabia", nameRu: "Саудовская Аравия", color: "#006c35", color2: "#ffffff", logo: "🇸🇦", isNational: true },
  { id: "iran", name: "Iran", nameRu: "Иран", color: "#239f40", color2: "#da0000", logo: "🇮🇷", isNational: true },
  { id: "australia", name: "Australia", nameRu: "Австралия", color: "#ffcd00", color2: "#00843d", logo: "🇦🇺", isNational: true },
  { id: "qatar", name: "Qatar", nameRu: "Катар", color: "#8a1538", color2: "#ffffff", logo: "🇶🇦", isNational: true },
  { id: "iraq", name: "Iraq", nameRu: "Ирак", color: "#ffffff", color2: "#007a3d", logo: "🇮🇶", isNational: true },
  { id: "china", name: "China", nameRu: "Китай", color: "#de2910", color2: "#ffde00", logo: "🇨🇳", isNational: true },
  { id: "kazakhstan", name: "Kazakhstan", nameRu: "Казахстан", color: "#00afca", color2: "#fec50c", logo: "🇰🇿", isNational: true },
  { id: "kyrgyzstan", name: "Kyrgyzstan", nameRu: "Кыргызстан", color: "#e8112d", color2: "#ffef00", logo: "🇰🇬", isNational: true },
  { id: "turkmenistan", name: "Turkmenistan", nameRu: "Туркменистан", color: "#00853e", color2: "#ffffff", logo: "🇹🇲", isNational: true },
  { id: "morocco", name: "Morocco", nameRu: "Марокко", color: "#c1272d", color2: "#006233", logo: "🇲🇦", isNational: true },
  { id: "senegal", name: "Senegal", nameRu: "Сенегал", color: "#00853f", color2: "#fdef42", logo: "🇸🇳", isNational: true },
  { id: "nigeria", name: "Nigeria", nameRu: "Нигерия", color: "#008751", color2: "#ffffff", logo: "🇳🇬", isNational: true },
  { id: "egypt", name: "Egypt", nameRu: "Египет", color: "#c8102e", color2: "#ffffff", logo: "🇪🇬", isNational: true },
  { id: "ghana", name: "Ghana", nameRu: "Гана", color: "#ce1126", color2: "#fcd116", logo: "🇬🇭", isNational: true },
  { id: "cameroon", name: "Cameroon", nameRu: "Камерун", color: "#007a5e", color2: "#ce1126", logo: "🇨🇲", isNational: true },
  { id: "algeria", name: "Algeria", nameRu: "Алжир", color: "#006233", color2: "#ffffff", logo: "🇩🇿", isNational: true },
  { id: "ivory_coast", name: "Ivory Coast", nameRu: "Кот-д'Ивуар", color: "#ff8200", color2: "#009e60", logo: "🇨🇮", isNational: true },
  { id: "usa", name: "USA", nameRu: "США", color: "#0a3161", color2: "#b31942", logo: "🇺🇸", isNational: true },
  { id: "mexico", name: "Mexico", nameRu: "Мексика", color: "#006847", color2: "#ce1126", logo: "🇲🇽", isNational: true },
  { id: "canada", name: "Canada", nameRu: "Канада", color: "#d52b1e", color2: "#ffffff", logo: "🇨🇦", isNational: true },
  { id: "costa_rica", name: "Costa Rica", nameRu: "Коста-Рика", color: "#002b7f", color2: "#ce1126", logo: "🇨🇷", isNational: true },
];

const CLUB_MAP = new Map<string, ClubInfo>(CLUB_DATA.map((c) => [c.id, c]));

export function getClub(id?: string | null): ClubInfo | undefined {
  if (!id) return undefined;
  return CLUB_MAP.get(id);
}

export default CLUB_DATA;
