// АВТОГЕНЕРАЦИЯ (см. /tmp/gen.js): клубы из data/clubs.go + логотипы TheSportsDB,
// сборные — все страны мира (флаг emoji). Битый логотип → градиентный бейдж.

export interface ClubInfo {
  id: string;
  name: string;
  nameRu: string;
  color: string;
  color2: string;
  logo: string;
  logoUrl?: string;
  isNational: boolean;
}

const CLUB_DATA: ClubInfo[] = [
  { id: "real_madrid", name: "Real Madrid", nameRu: "Реал Мадрид", color: "#ffffff", color2: "#1a3c8c", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/vwvwrw1473502969.png" },
  { id: "barcelona", name: "Barcelona", nameRu: "Барселона", color: "#a50044", color2: "#004d98", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/wq9sir1639406443.png" },
  { id: "man_city", name: "Manchester City", nameRu: "Манчестер Сити", color: "#6cabdd", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/vwpvry1467462651.png" },
  { id: "man_utd", name: "Manchester United", nameRu: "Манчестер Юнайтед", color: "#da291c", color2: "#fbe122", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/xzqdr11517660252.png" },
  { id: "liverpool", name: "Liverpool", nameRu: "Ливерпуль", color: "#c8102e", color2: "#f6eb61", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/kfaher1737969724.png" },
  { id: "chelsea", name: "Chelsea", nameRu: "Челси", color: "#034694", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/yvwvtu1448813215.png" },
  { id: "arsenal", name: "Arsenal", nameRu: "Арсенал", color: "#ef0107", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/uyhbfe1612467038.png" },
  { id: "psg", name: "Paris Saint-Germain", nameRu: "ПСЖ", color: "#003170", color2: "#da291c", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/26f50y1705434178.png" },
  { id: "bayern", name: "Bayern München", nameRu: "Бавария", color: "#dc052d", color2: "#0066b2", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/01ogkh1716960412.png" },
  { id: "dortmund", name: "Borussia Dortmund", nameRu: "Боруссия Дортмунд", color: "#fde100", color2: "#000000", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/tqo8ge1716960353.png" },
  { id: "juventus", name: "Juventus", nameRu: "Ювентус", color: "#000000", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/uxf0gr1742983727.png" },
  { id: "inter", name: "Inter Milan", nameRu: "Интер", color: "#003399", color2: "#000000", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/ryhu6d1617113103.png" },
  { id: "ac_milan", name: "AC Milan", nameRu: "Милан", color: "#fb090b", color2: "#000000", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/wvspur1448806617.png" },
  { id: "atletico", name: "Atlético Madrid", nameRu: "Атлетико", color: "#ce3524", color2: "#272e6b", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/0ulh3q1719984315.png" },
  { id: "chelsea_w", name: "Ajax", nameRu: "Аякс", color: "#d2122e", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/zg9tii1755495289.png" },
  { id: "brazil", name: "Brazil", nameRu: "Бразилия", color: "#009c3b", color2: "#fedf00", logo: "🇧🇷", isNational: true },
  { id: "argentina", name: "Argentina", nameRu: "Аргентина", color: "#74acdf", color2: "#ffffff", logo: "🇦🇷", isNational: true },
  { id: "france", name: "France", nameRu: "Франция", color: "#002395", color2: "#ffffff", logo: "🇫🇷", isNational: true },
  { id: "england", name: "England", nameRu: "Англия", color: "#ffffff", color2: "#cf081f", logo: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", isNational: true },
  { id: "germany", name: "Germany", nameRu: "Германия", color: "#ffffff", color2: "#000000", logo: "🇩🇪", isNational: true },
  { id: "spain", name: "Spain", nameRu: "Испания", color: "#c60b1e", color2: "#ffc400", logo: "🇪🇸", isNational: true },
  { id: "portugal", name: "Portugal", nameRu: "Португалия", color: "#006600", color2: "#ff0000", logo: "🇵🇹", isNational: true },
  { id: "italy", name: "Italy", nameRu: "Италия", color: "#003399", color2: "#ffffff", logo: "🇮🇹", isNational: true },
  { id: "uzbekistan", name: "Uzbekistan", nameRu: "Узбекистан", color: "#1eb53a", color2: "#0099b5", logo: "🇺🇿", isNational: true },
  { id: "tajikistan", name: "Tajikistan", nameRu: "Таджикистан", color: "#cc0000", color2: "#006600", logo: "🇹🇯", isNational: true },
  { id: "tottenham", name: "Tottenham Hotspur", nameRu: "Тоттенхэм", color: "#ffffff", color2: "#132257", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/dfyfhl1604094109.png" },
  { id: "newcastle", name: "Newcastle United", nameRu: "Ньюкасл", color: "#241f20", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/lhwuiz1621593302.png" },
  { id: "aston_villa", name: "Aston Villa", nameRu: "Астон Вилла", color: "#670e36", color2: "#95bfe5", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/jykrpv1717309891.png" },
  { id: "west_ham", name: "West Ham United", nameRu: "Вест Хэм", color: "#7a263a", color2: "#1bb1e7", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/yutyxs1467459956.png" },
  { id: "brighton", name: "Brighton & Hove Albion", nameRu: "Брайтон", color: "#0057b8", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/zn0x7h1605371909.png" },
  { id: "wolves", name: "Wolverhampton", nameRu: "Вулверхэмптон", color: "#fdb913", color2: "#231f20", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/u9qr031621593327.png" },
  { id: "crystal_palace", name: "Crystal Palace", nameRu: "Кристал Пэлас", color: "#1b458f", color2: "#c4122e", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/ia6i3m1656014992.png" },
  { id: "fulham", name: "Fulham", nameRu: "Фулхэм", color: "#ffffff", color2: "#000000", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/xwwvyt1448811086.png" },
  { id: "brentford", name: "Brentford", nameRu: "Брентфорд", color: "#e30613", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/grv1aw1546453779.png" },
  { id: "everton", name: "Everton", nameRu: "Эвертон", color: "#003399", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/eqayrf1523184794.png" },
  { id: "nottingham", name: "Nottingham Forest", nameRu: "Ноттингем Форест", color: "#dd0000", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/1i2kvh1719918076.png" },
  { id: "leeds", name: "Leeds United", nameRu: "Лидс", color: "#ffffff", color2: "#1d428a", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/jcgrml1756649030.png" },
  { id: "sevilla", name: "Sevilla", nameRu: "Севилья", color: "#d8112a", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/vpsqqx1473502977.png" },
  { id: "real_betis", name: "Real Betis", nameRu: "Бетис", color: "#00954c", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/2oqulv1663245386.png" },
  { id: "villarreal", name: "Villarreal", nameRu: "Вильярреал", color: "#ffe667", color2: "#005187", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/vrypqy1473503073.png" },
  { id: "real_sociedad", name: "Real Sociedad", nameRu: "Реал Сосьедад", color: "#0067b1", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/vptvpr1473502986.png" },
  { id: "athletic", name: "Athletic Bilbao", nameRu: "Атлетик Бильбао", color: "#ee2523", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/68w7fe1639408210.png" },
  { id: "valencia", name: "Valencia", nameRu: "Валенсия", color: "#ffffff", color2: "#f18e00", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/dm8l6o1655594864.png" },
  { id: "girona", name: "Girona", nameRu: "Жирона", color: "#d50032", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/kfu7zu1659897499.png" },
  { id: "celta", name: "Celta Vigo", nameRu: "Сельта", color: "#8ac3ee", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/xfjtku1690436219.png" },
  { id: "napoli", name: "Napoli", nameRu: "Наполи", color: "#12a0d7", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/l8qyxv1742982541.png" },
  { id: "roma", name: "AS Roma", nameRu: "Рома", color: "#8e1f2f", color2: "#f0bc42", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/jwro2s1760820674.png" },
  { id: "lazio", name: "Lazio", nameRu: "Лацио", color: "#87d8f7", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/rwqyvs1448806608.png" },
  { id: "atalanta", name: "Atalanta", nameRu: "Аталанта", color: "#1d1d1b", color2: "#005ca9", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/qix5ku1780561327.png" },
  { id: "fiorentina", name: "Fiorentina", nameRu: "Фиорентина", color: "#592c82", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/hc8nhu1656098030.png" },
  { id: "bologna", name: "Bologna", nameRu: "Болонья", color: "#1a2f48", color2: "#a01e20", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/2qi1u31655592366.png" },
  { id: "torino", name: "Torino", nameRu: "Торино", color: "#881600", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/xxprty1448806802.png" },
  { id: "leipzig", name: "RB Leipzig", nameRu: "Лейпциг", color: "#dd0741", color2: "#001f47", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/zjgapo1594244951.png" },
  { id: "leverkusen", name: "Bayer Leverkusen", nameRu: "Байер", color: "#e32219", color2: "#000000", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/3x9k851726760113.png" },
  { id: "frankfurt", name: "Eintracht Frankfurt", nameRu: "Айнтрахт", color: "#000000", color2: "#e1000f", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/rurwpy1473453269.png" },
  { id: "wolfsburg", name: "VfL Wolfsburg", nameRu: "Вольфсбург", color: "#65b32e", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/ci9trv1778399557.png" },
  { id: "stuttgart", name: "VfB Stuttgart", nameRu: "Штутгарт", color: "#ffffff", color2: "#e30613", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/yppyux1473454085.png" },
  { id: "gladbach", name: "Borussia M'gladbach", nameRu: "Боруссия М", color: "#ffffff", color2: "#000000", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/sysurw1473453380.png" },
  { id: "freiburg", name: "SC Freiburg", nameRu: "Фрайбург", color: "#000000", color2: "#e2001a", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/dkufe01630021084.png" },
  { id: "marseille", name: "Olympique Marseille", nameRu: "Марсель", color: "#2faee0", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/c6bazh1779212287.png" },
  { id: "lyon", name: "Olympique Lyon", nameRu: "Лион", color: "#ffffff", color2: "#e2001a", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/blk9771656932845.png" },
  { id: "monaco", name: "AS Monaco", nameRu: "Монако", color: "#e51b22", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/fl2ti01649168915.png" },
  { id: "lille", name: "Lille", nameRu: "Лилль", color: "#e01e24", color2: "#001b50", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/txcsg21741597962.png" },
  { id: "nice", name: "OGC Nice", nameRu: "Ницца", color: "#c8102e", color2: "#000000", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/msy7ly1621593859.png" },
  { id: "rennes", name: "Stade Rennais", nameRu: "Ренн", color: "#e23737", color2: "#000000", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/ypturx1473504818.png" },
  { id: "lens", name: "RC Lens", nameRu: "Ланс", color: "#ffe500", color2: "#e2001a", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/3pxoum1598797195.png" },
  { id: "benfica", name: "Benfica", nameRu: "Бенфика", color: "#e30613", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/hj4kyc1781152436.png" },
  { id: "porto", name: "FC Porto", nameRu: "Порту", color: "#00428c", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/86rrtg1628850959.png" },
  { id: "sporting", name: "Sporting CP", nameRu: "Спортинг", color: "#008057", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/ohj6ih1628855978.png" },
  { id: "braga", name: "SC Braga", nameRu: "Брага", color: "#e30613", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/8g4aod1678717261.png" },
  { id: "ajax", name: "Ajax", nameRu: "Аякс", color: "#d2122e", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/zg9tii1755495289.png" },
  { id: "psv", name: "PSV Eindhoven", nameRu: "ПСВ", color: "#ed1c24", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/xfsz6i1721297428.png" },
  { id: "feyenoord", name: "Feyenoord", nameRu: "Фейеноорд", color: "#e30613", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/uturtx1473534803.png" },
  { id: "celtic", name: "Celtic", nameRu: "Селтик", color: "#16973b", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/3uv1641758780002.png" },
  { id: "rangers", name: "Rangers", nameRu: "Рейнджерс", color: "#1b458f", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/ti24j61614290048.png" },
  { id: "galatasaray", name: "Galatasaray", nameRu: "Галатасарай", color: "#a90432", color2: "#fbb800", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/io7jk21767941298.png" },
  { id: "fenerbahce", name: "Fenerbahçe", nameRu: "Фенербахче", color: "#093a7c", color2: "#ffed00", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/twxxvs1448199691.png" },
  { id: "besiktas", name: "Beşiktaş", nameRu: "Бешикташ", color: "#000000", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/svo05k1776827439.png" },
  { id: "shakhtar", name: "Shakhtar Donetsk", nameRu: "Шахтёр", color: "#f47b20", color2: "#000000", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/sqrxsr1421791799.png" },
  { id: "club_brugge", name: "Club Brugge", nameRu: "Брюгге", color: "#005baa", color2: "#000000", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/mz8y0q1771129880.png" },
  { id: "salzburg", name: "RB Salzburg", nameRu: "Зальцбург", color: "#e2001a", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://www.thesportsdb.com/images/media/team/badge/nc2cua1781541639.png" },
  { id: "boca", name: "Boca Juniors", nameRu: "Бока Хуниорс", color: "#003f88", color2: "#fcb813", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/bm7krb1775741582.png" },
  { id: "river_plate", name: "River Plate", nameRu: "Ривер Плейт", color: "#ffffff", color2: "#e6002d", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/03dmi31645539717.png" },
  { id: "flamengo", name: "Flamengo", nameRu: "Фламенго", color: "#c52613", color2: "#000000", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/syptwx1473538074.png" },
  { id: "palmeiras", name: "Palmeiras", nameRu: "Палмейрас", color: "#006437", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/vsqwqp1473538105.png" },
  { id: "corinthians", name: "Corinthians", nameRu: "Коринтианс", color: "#000000", color2: "#ffffff", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/vvuvps1473538042.png" },
  { id: "sao_paulo", name: "São Paulo", nameRu: "Сан-Паулу", color: "#ffffff", color2: "#e30613", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/sxpupx1473538135.png" },
  { id: "santos", name: "Santos", nameRu: "Сантос", color: "#ffffff", color2: "#000000", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/j8xk9g1679447486.png" },
  { id: "gremio", name: "Grêmio", nameRu: "Гремио", color: "#0d80bf", color2: "#000000", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/uvpwyt1473538089.png" },
  { id: "netherlands", name: "Netherlands", nameRu: "Нидерланды", color: "#ff7d00", color2: "#ffffff", logo: "🇳🇱", isNational: true },
  { id: "belgium", name: "Belgium", nameRu: "Бельгия", color: "#e30613", color2: "#ffe500", logo: "🇧🇪", isNational: true },
  { id: "croatia", name: "Croatia", nameRu: "Хорватия", color: "#e30613", color2: "#ffffff", logo: "🇭🇷", isNational: true },
  { id: "denmark", name: "Denmark", nameRu: "Дания", color: "#c8102e", color2: "#ffffff", logo: "🇩🇰", isNational: true },
  { id: "switzerland", name: "Switzerland", nameRu: "Швейцария", color: "#d52b1e", color2: "#ffffff", logo: "🇨🇭", isNational: true },
  { id: "poland", name: "Poland", nameRu: "Польша", color: "#ffffff", color2: "#dc143c", logo: "🇵🇱", isNational: true },
  { id: "sweden", name: "Sweden", nameRu: "Швеция", color: "#006aa7", color2: "#fecc00", logo: "🇸🇪", isNational: true },
  { id: "ukraine", name: "Ukraine", nameRu: "Украина", color: "#005bbb", color2: "#ffd500", logo: "🇺🇦", isNational: true },
  { id: "serbia", name: "Serbia", nameRu: "Сербия", color: "#c6363c", color2: "#ffffff", logo: "🇷🇸", isNational: true },
  { id: "turkey", name: "Turkey", nameRu: "Турция", color: "#e30a17", color2: "#ffffff", logo: "🇹🇷", isNational: true },
  { id: "wales", name: "Wales", nameRu: "Уэльс", color: "#c8102e", color2: "#ffffff", logo: "🏴󠁧󠁢󠁷󠁬󠁳󠁿", isNational: true },
  { id: "scotland", name: "Scotland", nameRu: "Шотландия", color: "#0065bd", color2: "#ffffff", logo: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", isNational: true },
  { id: "austria_nt", name: "Austria", nameRu: "Австрия", color: "#ef3340", color2: "#ffffff", logo: "🇦🇹", isNational: true },
  { id: "russia", name: "Russia", nameRu: "Россия", color: "#ffffff", color2: "#d52b1e", logo: "🇷🇺", isNational: true },
  { id: "uruguay", name: "Uruguay", nameRu: "Уругвай", color: "#5cbfeb", color2: "#ffffff", logo: "🇺🇾", isNational: true },
  { id: "colombia", name: "Colombia", nameRu: "Колумбия", color: "#fcd116", color2: "#003893", logo: "🇨🇴", isNational: true },
  { id: "chile", name: "Chile", nameRu: "Чили", color: "#d52b1e", color2: "#0039a6", logo: "🇨🇱", isNational: true },
  { id: "peru", name: "Peru", nameRu: "Перу", color: "#d91023", color2: "#ffffff", logo: "🇵🇪", isNational: true },
  { id: "ecuador", name: "Ecuador", nameRu: "Эквадор", color: "#ffd100", color2: "#0072ce", logo: "🇪🇨", isNational: true },
  { id: "paraguay", name: "Paraguay", nameRu: "Парагвай", color: "#d52b1e", color2: "#0038a8", logo: "🇵🇾", isNational: true },
  { id: "japan", name: "Japan", nameRu: "Япония", color: "#0a1f8f", color2: "#ffffff", logo: "🇯🇵", isNational: true },
  { id: "south_korea", name: "South Korea", nameRu: "Южная Корея", color: "#c60c30", color2: "#003478", logo: "🇰🇷", isNational: true },
  { id: "saudi_arabia", name: "Saudi Arabia", nameRu: "Саудовская Аравия", color: "#006c35", color2: "#ffffff", logo: "🇸🇦", isNational: true },
  { id: "iran", name: "Iran", nameRu: "Иран", color: "#239f40", color2: "#da0000", logo: "🇮🇷", isNational: true },
  { id: "australia", name: "Australia", nameRu: "Австралия", color: "#ffcd00", color2: "#00843d", logo: "🇦🇺", isNational: true },
  { id: "qatar", name: "Qatar", nameRu: "Катар", color: "#8a1538", color2: "#ffffff", logo: "🇶🇦", isNational: true },
  { id: "iraq", name: "Iraq", nameRu: "Ирак", color: "#ffffff", color2: "#007a3d", logo: "🇮🇶", isNational: true },
  { id: "china", name: "China", nameRu: "Китай", color: "#de2910", color2: "#ffde00", logo: "🇨🇳", isNational: true },
  { id: "kazakhstan", name: "Kazakhstan", nameRu: "Казахстан", color: "#00afca", color2: "#fec50c", logo: "🇰🇿", isNational: true },
  { id: "kyrgyzstan", name: "Kyrgyzstan", nameRu: "Кыргызстан", color: "#e8112d", color2: "#ffef00", logo: "🇰🇬", isNational: true },
  { id: "turkmenistan", name: "Turkmenistan", nameRu: "Туркменистан", color: "#00853e", color2: "#ffffff", logo: "🇹🇲", isNational: true },
  { id: "morocco", name: "Morocco", nameRu: "Марокко", color: "#c1272d", color2: "#006233", logo: "🇲🇦", isNational: true },
  { id: "senegal", name: "Senegal", nameRu: "Сенегал", color: "#00853f", color2: "#fdef42", logo: "🇸🇳", isNational: true },
  { id: "nigeria", name: "Nigeria", nameRu: "Нигерия", color: "#008751", color2: "#ffffff", logo: "🇳🇬", isNational: true },
  { id: "egypt", name: "Egypt", nameRu: "Египет", color: "#c8102e", color2: "#ffffff", logo: "🇪🇬", isNational: true },
  { id: "ghana", name: "Ghana", nameRu: "Гана", color: "#ce1126", color2: "#fcd116", logo: "🇬🇭", isNational: true },
  { id: "cameroon", name: "Cameroon", nameRu: "Камерун", color: "#007a5e", color2: "#ce1126", logo: "🇨🇲", isNational: true },
  { id: "algeria", name: "Algeria", nameRu: "Алжир", color: "#006233", color2: "#ffffff", logo: "🇩🇿", isNational: true },
  { id: "ivory_coast", name: "Ivory Coast", nameRu: "Кот-д'Ивуар", color: "#ff8200", color2: "#009e60", logo: "🇨🇮", isNational: true },
  { id: "usa", name: "USA", nameRu: "США", color: "#0a3161", color2: "#b31942", logo: "🇺🇸", isNational: true },
  { id: "mexico", name: "Mexico", nameRu: "Мексика", color: "#006847", color2: "#ce1126", logo: "🇲🇽", isNational: true },
  { id: "canada", name: "Canada", nameRu: "Канада", color: "#d52b1e", color2: "#ffffff", logo: "🇨🇦", isNational: true },
  { id: "costa_rica", name: "Costa Rica", nameRu: "Коста-Рика", color: "#002b7f", color2: "#ce1126", logo: "🇨🇷", isNational: true },
  { id: "pakhtakor", name: "Pakhtakor", nameRu: "Pakhtakor", color: "#312bab", color2: "#45206f", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/9leeml1675712410.png" },
  { id: "nasaf", name: "Nasaf", nameRu: "Nasaf", color: "#ab2b98", color2: "#6f2042", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/ezlsi91724091113.png" },
  { id: "bunyodkor", name: "Bunyodkor", nameRu: "Bunyodkor", color: "#ab2b7a", color2: "#6f2030", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/crm3u81583080177.png" },
  { id: "agmk", name: "AGMK", nameRu: "AGMK", color: "#45ab2b", color2: "#206f31", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/35f4321693024889.png" },
  { id: "navbahor_namangan", name: "Navbahor Namangan", nameRu: "Navbahor Namangan", color: "#2bab67", color2: "#206f66", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/p4dsce1656015182.png" },
  { id: "lokomotiv_tashkent", name: "Lokomotiv Tashkent", nameRu: "Lokomotiv Tashkent", color: "#2bab2f", color2: "#206f43", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/hof90x1583080445.png" },
  { id: "sogdiana_jizzakh", name: "Sogdiana Jizzakh", nameRu: "Sogdiana Jizzakh", color: "#ab762b", color2: "#6f6f20", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/5nfr6x1735489606.png" },
  { id: "istiklol_dushanbe", name: "Istiklol Dushanbe", nameRu: "Istiklol Dushanbe", color: "#2bab3e", color2: "#206f4d", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/giywuj1583952811.png" },
  { id: "khujand", name: "Khujand", nameRu: "Khujand", color: "#65ab2b", color2: "#236f20", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/l7ofup1583952825.png" },
  { id: "spartak_moscow", name: "Spartak Moscow", nameRu: "Spartak Moscow", color: "#742bab", color2: "#6d206f", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/zpj2el1754674286.png" },
  { id: "zenit_saint_petersburg", name: "Zenit Saint Petersburg", nameRu: "Zenit Saint Petersburg", color: "#ab2b81", color2: "#6f2034", logo: "⚽", isNational: false, logoUrl: "https://www.thesportsdb.com/images/media/team/badge/t20z2n1782186629.png" },
  { id: "cska_moscow", name: "CSKA Moscow", nameRu: "CSKA Moscow", color: "#2b89ab", color2: "#20396f", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/1hf19s1681319986.png" },
  { id: "lokomotiv_moscow", name: "Lokomotiv Moscow", nameRu: "Lokomotiv Moscow", color: "#742bab", color2: "#6d206f", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/tuyrur1473452310.png" },
  { id: "krasnodar", name: "Krasnodar", nameRu: "Krasnodar", color: "#ab542b", color2: "#6f5a20", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/srxryu1473452272.png" },
  { id: "rubin_kazan", name: "Rubin Kazan", nameRu: "Rubin Kazan", color: "#7a2bab", color2: "#6f206c", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/hp9kw81579347672.png" },
  { id: "al_ittihad_misurata", name: "Al-Ittihad Misurata", nameRu: "Al-Ittihad Misurata", color: "#2baba5", color2: "#20526f", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/1z3n911666899419.png" },
  { id: "olympiacos", name: "Olympiacos", nameRu: "Olympiacos", color: "#4d2bab", color2: "#56206f", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/xckasq1721291508.png" },
  { id: "panathinaikos", name: "Panathinaikos", nameRu: "Panathinaikos", color: "#2baba7", color2: "#20516f", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/vtpwwt1448208397.png" },
  { id: "aek_athens", name: "AEK Athens", nameRu: "AEK Athens", color: "#8d2bab", color2: "#6f2060", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/4nogst1602773624.png" },
  { id: "paok", name: "PAOK", nameRu: "PAOK", color: "#692bab", color2: "#67206f", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/m15zsh1602774126.png" },
  { id: "dynamo_kyiv", name: "Dynamo Kyiv", nameRu: "Dynamo Kyiv", color: "#ab4f2b", color2: "#6f5720", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/ktbncx1781158762.png" },
  { id: "crvena_zvezda", name: "Crvena Zvezda", nameRu: "Crvena Zvezda", color: "#ab362b", color2: "#6f4720", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/osgmbz1781157114.png" },
  { id: "partizan_belgrade", name: "Partizan Belgrade", nameRu: "Partizan Belgrade", color: "#362bab", color2: "#47206f", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/xe41k11781157208.png" },
  { id: "dinamo_zagreb", name: "Dinamo Zagreb", nameRu: "Dinamo Zagreb", color: "#2b65ab", color2: "#20236f", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/araidi1579955395.png" },
  { id: "anderlecht", name: "Anderlecht", nameRu: "Anderlecht", color: "#632bab", color2: "#63206f", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/auindn1771129464.png" },
  { id: "genk", name: "Genk", nameRu: "Genk", color: "#a92bab", color2: "#6f204f", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/tp06te1534875918.png" },
  { id: "las_palmas", name: "Las Palmas", nameRu: "Las Palmas", color: "#ab2b2f", color2: "#6f3e20", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/mmhyb11616443601.png" },
  { id: "getafe", name: "Getafe", nameRu: "Getafe", color: "#ab512b", color2: "#6f5820", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/eyh2891655594452.png" },
  { id: "osasuna", name: "Osasuna", nameRu: "Osasuna", color: "#2b5aab", color2: "#24206f", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/rvspvt1473502960.png" },
  { id: "rayo_vallecano", name: "Rayo Vallecano", nameRu: "Rayo Vallecano", color: "#ab5a2b", color2: "#6f5e20", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/nzhu941655595465.png" },
  { id: "mallorca", name: "Mallorca", nameRu: "Mallorca", color: "#2b31ab", color2: "#3d206f", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/ssptsx1473503730.png" },
  { id: "genoa", name: "Genoa", nameRu: "Genoa", color: "#2bab40", color2: "#206f4e", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/52s8dn1655553600.png" },
  { id: "monza", name: "Monza", nameRu: "Monza", color: "#ab2b9c", color2: "#6f2045", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/bxearg1603170113.png" },
  { id: "lecce", name: "Lecce", nameRu: "Lecce", color: "#2b33ab", color2: "#3c206f", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/j4vznr1567365249.png" },
  { id: "udinese", name: "Udinese", nameRu: "Udinese", color: "#58ab2b", color2: "#206f25", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/vwvstr1448806811.png" },
  { id: "cagliari", name: "Cagliari", nameRu: "Cagliari", color: "#2bab2f", color2: "#206f43", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/wvsvxt1447534471.png" },
  { id: "empoli", name: "Empoli", nameRu: "Empoli", color: "#892bab", color2: "#6f2063", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/c1ie6b1622561483.png" },
  { id: "hoffenheim", name: "Hoffenheim", nameRu: "Hoffenheim", color: "#832bab", color2: "#6f2067", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/9hwvb21621593919.png" },
  { id: "werder_bremen", name: "Werder Bremen", nameRu: "Werder Bremen", color: "#ab332b", color2: "#6f4620", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/tkvqan1716960454.png" },
  { id: "mainz", name: "Mainz", nameRu: "Mainz", color: "#ab2d2b", color2: "#6f4220", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/fhm9v51552134916.png" },
  { id: "augsburg", name: "Augsburg", nameRu: "Augsburg", color: "#2bab4d", color2: "#206f56", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/xqyyvq1473453233.png" },
  { id: "union_berlin", name: "Union Berlin", nameRu: "Union Berlin", color: "#2b47ab", color2: "#30206f", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/q0o5001599679795.png" },
  { id: "hertha", name: "Hertha", nameRu: "Hertha", color: "#ab2ba3", color2: "#6f2049", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/8okmtm1621593943.png" },
  { id: "schalke_04", name: "Schalke 04", nameRu: "Schalke 04", color: "#6d2bab", color2: "#69206f", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/hnci291621593978.png" },
  { id: "toulouse", name: "Toulouse", nameRu: "Toulouse", color: "#ab512b", color2: "#6f5820", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/17eqox1688449282.png" },
  { id: "montpellier", name: "Montpellier", nameRu: "Montpellier", color: "#3e2bab", color2: "#4d206f", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/8wn9x31750879448.png" },
  { id: "strasbourg", name: "Strasbourg", nameRu: "Strasbourg", color: "#ab2b5a", color2: "#6f2420", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/b8k77w1766625501.png" },
  { id: "nantes", name: "Nantes", nameRu: "Nantes", color: "#902bab", color2: "#6f205f", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/mla9x61678808018.png" },
  { id: "brest", name: "Brest", nameRu: "Brest", color: "#ab2ba7", color2: "#6f204b", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/z69be41598797026.png" },
  { id: "sporting_atl_tico", name: "Sporting Atlético", nameRu: "Sporting Atlético", color: "#422bab", color2: "#4f206f", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/oom09m1578831384.png" },
  { id: "kawasaki_frontale", name: "Kawasaki Frontale", nameRu: "Kawasaki Frontale", color: "#a9ab2b", color2: "#4d6f20", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/c6pot51578239112.png" },
  { id: "yokohama_f_marinos", name: "Yokohama F Marinos", nameRu: "Yokohama F Marinos", color: "#2babab", color2: "#204e6f", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/rgeshm1578240000.png" },
  { id: "vissel_kobe", name: "Vissel Kobe", nameRu: "Vissel Kobe", color: "#472bab", color2: "#52206f", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/2axjch1578239819.png" },
  { id: "jeonbuk_hyundai_motors", name: "Jeonbuk Hyundai Motors", nameRu: "Jeonbuk Hyundai Motors", color: "#ab2ba7", color2: "#6f204b", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/8jif3b1747853225.png" },
  { id: "ulsan_hd", name: "Ulsan HD", nameRu: "Ulsan HD", color: "#ab2b8b", color2: "#6f203a", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/0wooic1706533767.png" },
  { id: "fc_seoul", name: "FC Seoul", nameRu: "FC Seoul", color: "#4f2bab", color2: "#57206f", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/31z1zf1579473186.png" },
  { id: "shanghai_port", name: "Shanghai Port", nameRu: "Shanghai Port", color: "#ab5a2b", color2: "#6f5e20", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/d9evs91776534441.png" },
  { id: "guangzhou_fc", name: "Guangzhou FC", nameRu: "Guangzhou FC", color: "#ab2b42", color2: "#6f3220", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/3nkgi61654266984.png" },
  { id: "la_galaxy", name: "LA Galaxy", nameRu: "LA Galaxy", color: "#ab2b47", color2: "#6f3020", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/ysyysr1420227188.png" },
  { id: "los_angeles_fc", name: "Los Angeles FC", nameRu: "Los Angeles FC", color: "#51ab2b", color2: "#206f29", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/7nbj2a1602103638.png" },
  { id: "inter_miami", name: "Inter Miami", nameRu: "Inter Miami", color: "#ab692b", color2: "#6f6720", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/m4it3e1602103647.png" },
  { id: "seattle_sounders", name: "Seattle Sounders", nameRu: "Seattle Sounders", color: "#2bab3a", color2: "#206f4a", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/2dy5cx1706711036.png" },
  { id: "am_rica", name: "América", nameRu: "América", color: "#aba72b", color2: "#516f20", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/amy1xs1581857392.png" },
  { id: "guadalajara", name: "Guadalajara", nameRu: "Guadalajara", color: "#2b69ab", color2: "#20256f", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/qt2hk81757606691.png" },
  { id: "tigres_uanl", name: "Tigres UANL", nameRu: "Tigres UANL", color: "#2bab67", color2: "#206f66", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/lh80fx1701423708.png" },
  { id: "monterrey", name: "Monterrey", nameRu: "Monterrey", color: "#2b4bab", color2: "#2d206f", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/yglj911721542561.png" },
  { id: "independiente", name: "Independiente", nameRu: "Independiente", color: "#2bab2f", color2: "#206f43", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/eki4nd1580842605.png" },
  { id: "racing_club", name: "Racing Club", nameRu: "Racing Club", color: "#81ab2b", color2: "#346f20", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/vi4mu41695734959.png" },
  { id: "v_lez_sarsfield", name: "Vélez Sarsfield", nameRu: "Vélez Sarsfield", color: "#2bab2d", color2: "#206f42", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/jo98m71517769587.png" },
  { id: "internacional", name: "Internacional", nameRu: "Internacional", color: "#2b4fab", color2: "#2b206f", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/yprvxx1473538097.png" },
  { id: "atl_tico_mineiro", name: "Atlético Mineiro", nameRu: "Atlético Mineiro", color: "#562bab", color2: "#5b206f", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/x5lixs1743742872.png" },
  { id: "botafogo", name: "Botafogo", nameRu: "Botafogo", color: "#2bab42", color2: "#206f4f", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/bs5mbw1733004596.png" },
  { id: "fluminense", name: "Fluminense", nameRu: "Fluminense", color: "#96ab2b", color2: "#416f20", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/stvvwp1473538082.png" },
  { id: "vasco_da_gama", name: "Vasco da Gama", nameRu: "Vasco da Gama", color: "#2bab36", color2: "#206f47", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/ynqlxo1630521109.png" },
  { id: "cruzeiro", name: "Cruzeiro", nameRu: "Cruzeiro", color: "#2bab9c", color2: "#20576f", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/upsvvu1473538059.png" },
  { id: "boavista", name: "Boavista", nameRu: "Boavista", color: "#2bab94", color2: "#205c6f", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/usi98v1628853974.png" },
  { id: "vit_ria", name: "Vitória", nameRu: "Vitória", color: "#ab3c2b", color2: "#6f4b20", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/tysrrx1473538156.png" },
  { id: "trabzonspor", name: "Trabzonspor", nameRu: "Trabzonspor", color: "#38ab2b", color2: "#206f39", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/96s34o1776827629.png" },
  { id: "i_stanbul_ba_ak_ehir", name: "İstanbul Başakşehir", nameRu: "İstanbul Başakşehir", color: "#2b74ab", color2: "#202c6f", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/895mqt1685993958.png" },
  { id: "al_sadd", name: "Al-Sadd", nameRu: "Al-Sadd", color: "#ab2b4d", color2: "#6f2c20", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/908a011774579337.png" },
  { id: "al_duhail", name: "Al-Duhail", nameRu: "Al-Duhail", color: "#ab2ba5", color2: "#6f204a", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/n1vtjm1577985347.png" },
  { id: "urawa_red_diamonds", name: "Urawa Red Diamonds", nameRu: "Urawa Red Diamonds", color: "#3cab2b", color2: "#206f36", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/ce3lhk1578239741.png" },
  { id: "al_nassr", name: "Al-Nassr", nameRu: "Al-Nassr", color: "#ab472b", color2: "#6f5220", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/84yvqi1748524565.png" },
  { id: "hamburg", name: "Hamburg", nameRu: "Hamburg", color: "#ab562b", color2: "#6f5b20", logo: "⚽", isNational: false, logoUrl: "https://r2.thesportsdb.com/images/media/team/badge/tvtppt1473453296.png" },
  { id: "afghanistan", name: "Afghanistan", nameRu: "Афганистан", color: "#ab332b", color2: "#6f4620", logo: "🇦🇫", isNational: true },
  { id: "albania", name: "Albania", nameRu: "Албания", color: "#2bab78", color2: "#206d6f", logo: "🇦🇱", isNational: true },
  { id: "angola", name: "Angola", nameRu: "Ангола", color: "#2b38ab", color2: "#39206f", logo: "🇦🇴", isNational: true },
  { id: "armenia", name: "Armenia", nameRu: "Армения", color: "#2b31ab", color2: "#3d206f", logo: "🇦🇲", isNational: true },
  { id: "azerbaijan", name: "Azerbaijan", nameRu: "Азербайджан", color: "#2b69ab", color2: "#20256f", logo: "🇦🇿", isNational: true },
  { id: "bahrain", name: "Bahrain", nameRu: "Бахрейн", color: "#ab2b42", color2: "#6f3220", logo: "🇧🇭", isNational: true },
  { id: "bangladesh", name: "Bangladesh", nameRu: "Бангладеш", color: "#8bab2b", color2: "#3a6f20", logo: "🇧🇩", isNational: true },
  { id: "belarus", name: "Belarus", nameRu: "Беларусь", color: "#2b4dab", color2: "#2c206f", logo: "🇧🇾", isNational: true },
  { id: "bolivia", name: "Bolivia", nameRu: "Боливия", color: "#2bab78", color2: "#206d6f", logo: "🇧🇴", isNational: true },
  { id: "bosniaandherzegovina", name: "Bosnia and Herzegovina", nameRu: "Босния и Герцеговина", color: "#9c2bab", color2: "#6f2057", logo: "🇧🇦", isNational: true },
  { id: "botswana", name: "Botswana", nameRu: "Ботсвана", color: "#2bab60", color2: "#206f62", logo: "🇧🇼", isNational: true },
  { id: "bulgaria", name: "Bulgaria", nameRu: "Болгария", color: "#4b2bab", color2: "#54206f", logo: "🇧🇬", isNational: true },
  { id: "burkinafaso", name: "Burkina Faso", nameRu: "Буркина-Фасо", color: "#83ab2b", color2: "#356f20", logo: "🇧🇫", isNational: true },
  { id: "burundi", name: "Burundi", nameRu: "Бурунди", color: "#76ab2b", color2: "#2d6f20", logo: "🇧🇮", isNational: true },
  { id: "cambodia", name: "Cambodia", nameRu: "Камбоджа", color: "#81ab2b", color2: "#346f20", logo: "🇰🇭", isNational: true },
  { id: "cuba", name: "Cuba", nameRu: "Куба", color: "#2bab94", color2: "#205c6f", logo: "🇨🇺", isNational: true },
  { id: "cyprus", name: "Cyprus", nameRu: "Кипр", color: "#8d2bab", color2: "#6f2060", logo: "🇨🇾", isNational: true },
  { id: "czechrepublic", name: "Czech Republic", nameRu: "Чехия", color: "#2d2bab", color2: "#42206f", logo: "🇨🇿", isNational: true },
  { id: "drcongo", name: "DR Congo", nameRu: "ДР Конго", color: "#ab2b3c", color2: "#6f3620", logo: "🇨🇩", isNational: true },
  { id: "dominicanrepublic", name: "Dominican Republic", nameRu: "Доминикана", color: "#ab382b", color2: "#6f4920", logo: "🇩🇴", isNational: true },
  { id: "elsalvador", name: "El Salvador", nameRu: "Сальвадор", color: "#2b94ab", color2: "#20406f", logo: "🇸🇻", isNational: true },
  { id: "estonia", name: "Estonia", nameRu: "Эстония", color: "#65ab2b", color2: "#236f20", logo: "🇪🇪", isNational: true },
  { id: "ethiopia", name: "Ethiopia", nameRu: "Эфиопия", color: "#2b3aab", color2: "#38206f", logo: "🇪🇹", isNational: true },
  { id: "finland", name: "Finland", nameRu: "Финляндия", color: "#2b96ab", color2: "#20416f", logo: "🇫🇮", isNational: true },
  { id: "gabon", name: "Gabon", nameRu: "Габон", color: "#2bab3a", color2: "#206f4a", logo: "🇬🇦", isNational: true },
  { id: "georgia", name: "Georgia", nameRu: "Грузия", color: "#51ab2b", color2: "#206f29", logo: "🇬🇪", isNational: true },
  { id: "greece", name: "Greece", nameRu: "Греция", color: "#2b87ab", color2: "#20386f", logo: "🇬🇷", isNational: true },
  { id: "guatemala", name: "Guatemala", nameRu: "Гватемала", color: "#2b98ab", color2: "#20426f", logo: "🇬🇹", isNational: true },
  { id: "guinea", name: "Guinea", nameRu: "Гвинея", color: "#6d2bab", color2: "#69206f", logo: "🇬🇳", isNational: true },
  { id: "honduras", name: "Honduras", nameRu: "Гондурас", color: "#ab9a2b", color2: "#586f20", logo: "🇭🇳", isNational: true },
  { id: "hungary", name: "Hungary", nameRu: "Венгрия", color: "#8dab2b", color2: "#3c6f20", logo: "🇭🇺", isNational: true },
  { id: "iceland", name: "Iceland", nameRu: "Исландия", color: "#ab2b2f", color2: "#6f3e20", logo: "🇮🇸", isNational: true },
  { id: "india", name: "India", nameRu: "Индия", color: "#2b60ab", color2: "#20206f", logo: "🇮🇳", isNational: true },
  { id: "indonesia", name: "Indonesia", nameRu: "Индонезия", color: "#ab2b56", color2: "#6f2720", logo: "🇮🇩", isNational: true },
  { id: "ireland", name: "Ireland", nameRu: "Ирландия", color: "#4fab2b", color2: "#206f2b", logo: "🇮🇪", isNational: true },
  { id: "israel", name: "Israel", nameRu: "Израиль", color: "#ab3c2b", color2: "#6f4b20", logo: "🇮🇱", isNational: true },
  { id: "jamaica", name: "Jamaica", nameRu: "Ямайка", color: "#ab2b45", color2: "#6f3120", logo: "🇯🇲", isNational: true },
  { id: "jordan", name: "Jordan", nameRu: "Иордания", color: "#782bab", color2: "#6f206d", logo: "🇯🇴", isNational: true },
  { id: "kenya", name: "Kenya", nameRu: "Кения", color: "#2b78ab", color2: "#202f6f", logo: "🇰🇪", isNational: true },
  { id: "kuwait", name: "Kuwait", nameRu: "Кувейт", color: "#2b2dab", color2: "#40206f", logo: "🇰🇼", isNational: true },
  { id: "laos", name: "Laos", nameRu: "Лаос", color: "#ab3e2b", color2: "#6f4d20", logo: "🇱🇦", isNational: true },
  { id: "latvia", name: "Latvia", nameRu: "Латвия", color: "#ab7e2b", color2: "#696f20", logo: "🇱🇻", isNational: true },
  { id: "lebanon", name: "Lebanon", nameRu: "Ливан", color: "#2b31ab", color2: "#3d206f", logo: "🇱🇧", isNational: true },
  { id: "libya", name: "Libya", nameRu: "Ливия", color: "#ab2b87", color2: "#6f2038", logo: "🇱🇾", isNational: true },
  { id: "lithuania", name: "Lithuania", nameRu: "Литва", color: "#2bab72", color2: "#206f6c", logo: "🇱🇹", isNational: true },
  { id: "luxembourg", name: "Luxembourg", nameRu: "Люксембург", color: "#40ab2b", color2: "#206f34", logo: "🇱🇺", isNational: true },
  { id: "northmacedonia", name: "North Macedonia", nameRu: "Северная Македония", color: "#2bab63", color2: "#206f63", logo: "🇲🇰", isNational: true },
  { id: "madagascar", name: "Madagascar", nameRu: "Мадагаскар", color: "#56ab2b", color2: "#206f27", logo: "🇲🇬", isNational: true },
  { id: "malaysia", name: "Malaysia", nameRu: "Малайзия", color: "#312bab", color2: "#45206f", logo: "🇲🇾", isNational: true },
  { id: "mali", name: "Mali", nameRu: "Мали", color: "#2baba5", color2: "#20526f", logo: "🇲🇱", isNational: true },
  { id: "malta", name: "Malta", nameRu: "Мальта", color: "#2bab8b", color2: "#20626f", logo: "🇲🇹", isNational: true },
  { id: "mauritania", name: "Mauritania", nameRu: "Мавритания", color: "#ab832b", color2: "#676f20", logo: "🇲🇷", isNational: true },
  { id: "moldova", name: "Moldova", nameRu: "Молдова", color: "#4d2bab", color2: "#56206f", logo: "🇲🇩", isNational: true },
  { id: "mongolia", name: "Mongolia", nameRu: "Монголия", color: "#ab2b5e", color2: "#6f2120", logo: "🇲🇳", isNational: true },
  { id: "montenegro", name: "Montenegro", nameRu: "Черногория", color: "#5e2bab", color2: "#60206f", logo: "🇲🇪", isNational: true },
  { id: "mozambique", name: "Mozambique", nameRu: "Мозамбик", color: "#ab5a2b", color2: "#6f5e20", logo: "🇲🇿", isNational: true },
  { id: "myanmar", name: "Myanmar", nameRu: "Мьянма", color: "#2b42ab", color2: "#32206f", logo: "🇲🇲", isNational: true },
  { id: "namibia", name: "Namibia", nameRu: "Намибия", color: "#ab872b", color2: "#646f20", logo: "🇳🇦", isNational: true },
  { id: "nepal", name: "Nepal", nameRu: "Непал", color: "#ab2b89", color2: "#6f2039", logo: "🇳🇵", isNational: true },
  { id: "newzealand", name: "New Zealand", nameRu: "Новая Зеландия", color: "#2bab60", color2: "#206f62", logo: "🇳🇿", isNational: true },
  { id: "nicaragua", name: "Nicaragua", nameRu: "Никарагуа", color: "#2b36ab", color2: "#3a206f", logo: "🇳🇮", isNational: true },
  { id: "niger", name: "Niger", nameRu: "Нигер", color: "#7eab2b", color2: "#326f20", logo: "🇳🇪", isNational: true },
  { id: "northkorea", name: "North Korea", nameRu: "КНДР", color: "#902bab", color2: "#6f205f", logo: "🇰🇵", isNational: true },
  { id: "norway", name: "Norway", nameRu: "Норвегия", color: "#96ab2b", color2: "#416f20", logo: "🇳🇴", isNational: true },
  { id: "oman", name: "Oman", nameRu: "Оман", color: "#ab762b", color2: "#6f6f20", logo: "🇴🇲", isNational: true },
  { id: "pakistan", name: "Pakistan", nameRu: "Пакистан", color: "#98ab2b", color2: "#426f20", logo: "🇵🇰", isNational: true },
  { id: "palestine", name: "Palestine", nameRu: "Палестина", color: "#ab2b65", color2: "#6f2023", logo: "🇵🇸", isNational: true },
  { id: "panama", name: "Panama", nameRu: "Панама", color: "#2b81ab", color2: "#20346f", logo: "🇵🇦", isNational: true },
  { id: "philippines", name: "Philippines", nameRu: "Филиппины", color: "#2baba5", color2: "#20526f", logo: "🇵🇭", isNational: true },
  { id: "romania", name: "Romania", nameRu: "Румыния", color: "#42ab2b", color2: "#206f32", logo: "🇷🇴", isNational: true },
  { id: "rwanda", name: "Rwanda", nameRu: "Руанда", color: "#ab2b60", color2: "#6f2020", logo: "🇷🇼", isNational: true },
  { id: "sierraleone", name: "Sierra Leone", nameRu: "Сьерра-Леоне", color: "#ab6d2b", color2: "#6f6920", logo: "🇸🇱", isNational: true },
  { id: "singapore", name: "Singapore", nameRu: "Сингапур", color: "#ab2b45", color2: "#6f3120", logo: "🇸🇬", isNational: true },
  { id: "slovakia", name: "Slovakia", nameRu: "Словакия", color: "#2f2bab", color2: "#43206f", logo: "🇸🇰", isNational: true },
  { id: "slovenia", name: "Slovenia", nameRu: "Словения", color: "#3e2bab", color2: "#4d206f", logo: "🇸🇮", isNational: true },
  { id: "somalia", name: "Somalia", nameRu: "Сомали", color: "#ab2b45", color2: "#6f3120", logo: "🇸🇴", isNational: true },
  { id: "southafrica", name: "South Africa", nameRu: "ЮАР", color: "#2bab9c", color2: "#20576f", logo: "🇿🇦", isNational: true },
  { id: "southsudan", name: "South Sudan", nameRu: "Южный Судан", color: "#ab2b89", color2: "#6f2039", logo: "🇸🇸", isNational: true },
  { id: "srilanka", name: "Sri Lanka", nameRu: "Шри-Ланка", color: "#2baba5", color2: "#20526f", logo: "🇱🇰", isNational: true },
  { id: "sudan", name: "Sudan", nameRu: "Судан", color: "#2b72ab", color2: "#202b6f", logo: "🇸🇩", isNational: true },
  { id: "syria", name: "Syria", nameRu: "Сирия", color: "#2b56ab", color2: "#27206f", logo: "🇸🇾", isNational: true },
  { id: "taiwan", name: "Taiwan", nameRu: "Тайвань", color: "#92ab2b", color2: "#3e6f20", logo: "🇹🇼", isNational: true },
  { id: "tanzania", name: "Tanzania", nameRu: "Танзания", color: "#9f2bab", color2: "#6f2056", logo: "🇹🇿", isNational: true },
  { id: "thailand", name: "Thailand", nameRu: "Таиланд", color: "#60ab2b", color2: "#206f20", logo: "🇹🇭", isNational: true },
  { id: "togo", name: "Togo", nameRu: "Того", color: "#542bab", color2: "#5a206f", logo: "🇹🇬", isNational: true },
  { id: "tunisia", name: "Tunisia", nameRu: "Тунис", color: "#a12bab", color2: "#6f2054", logo: "🇹🇳", isNational: true },
  { id: "uganda", name: "Uganda", nameRu: "Уганда", color: "#9a2bab", color2: "#6f2058", logo: "🇺🇬", isNational: true },
  { id: "uae", name: "UAE", nameRu: "ОАЭ", color: "#3e2bab", color2: "#4d206f", logo: "🇦🇪", isNational: true },
  { id: "northernireland", name: "Northern Ireland", nameRu: "Северная Ирландия", color: "#2bab76", color2: "#206f6f", logo: "🏴", isNational: true },
  { id: "venezuela", name: "Venezuela", nameRu: "Венесуэла", color: "#2bab60", color2: "#206f62", logo: "🇻🇪", isNational: true },
  { id: "vietnam", name: "Vietnam", nameRu: "Вьетнам", color: "#ab4d2b", color2: "#6f5620", logo: "🇻🇳", isNational: true },
  { id: "yemen", name: "Yemen", nameRu: "Йемен", color: "#ab2b6b", color2: "#6f2027", logo: "🇾🇪", isNational: true },
  { id: "zambia", name: "Zambia", nameRu: "Замбия", color: "#33ab2b", color2: "#206f3c", logo: "🇿🇲", isNational: true },
  { id: "zimbabwe", name: "Zimbabwe", nameRu: "Зимбабве", color: "#2b58ab", color2: "#25206f", logo: "🇿🇼", isNational: true },
];

const CLUB_MAP = new Map<string, ClubInfo>(CLUB_DATA.map((c) => [c.id, c]));

export function getClub(id?: string | null): ClubInfo | undefined {
  if (!id) return undefined;
  return CLUB_MAP.get(id);
}

export default CLUB_DATA;
